# Generated by Django 3.2 on 2023-09-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Пользователь с такой почтой уже существует'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
