# Generated by Django 3.2 on 2023-09-30 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230930_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Hазвание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0, message='Это произведение слишком старо для нас'), django.core.validators.MaxValueValidator(2023, message='Мы не можем заглядывать в будущее')], verbose_name='Год выхода'),
        ),
    ]
